version: '3.8'

services:
  main-db:
    build: ./db
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=netflix
    command: "postgres -c config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - ./data:/data
  replica-db:
    build: 
      context: ./db
      dockerfile: Dockerfile.replica
    ports:
      - "5002:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=netflix
    command: "postgres -c config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - ./data:/data
    depends_on:
    - main-db